name: Build Docker Image

on:
  push:
    branches:
      - main # workflow on main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # code repo code

    - name: Build Docker image
      run: |
        docker build -t my-custom-ubuntu-image:latest .
