name: Build Docker Image

on:
  push:
    branches:
      - main # workflow on main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # code repo code
    - name: Install Dependencies & Jit CLI
      run: |
        sudo apt-get update && sudo apt-get install -y curl git
        curl -L https://jit-cli.s3.us-east-1.amazonaws.com/jit-cli/latest/jit-cli-amd64-slim -o jit-cli
        chmod +x jit-cli

    - name: Pull DVWA image
      run: docker pull vulnerables/web-dvwa:latest

    - name: Run Jit CLI Scan
      env:
        # Needed for communicating Jit BE
        JIT_CLIENT_ID: ${{ secrets.JIT_CLIENT_ID }}
        JIT_SECRET_KEY: ${{ secrets.JIT_SECRET_KEY }}
      run: |
        ./jit-cli container \
          --image vulnerables/web-dvwa:latest \
          --tracking-name my-ubuntu-test-image \
          --fail-on-findings \
          --add-to-backlog
